name       : bitwarden-desktop
version    : 2022.6.2
release    : 2
source     :
    - https://github.com/bitwarden/clients/archive/refs/tags/desktop-v2022.6.2.tar.gz : 35aaf0c7689a2dd4d3e9844714dd306dea84063f17d1a875cbedefe4bdc04959
license    : GPL-3.0-only
component  : security
summary    : A secure and free password manager for all of your devices
description: A secure and free password manager for all of your devices
networking : yes
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pangocairo)
    - pkgconfig(xtst)
    - cups-devel
    - git
    - jq
    - nodejs
rundeps    :
    - nodejs
setup      : |
    export ELECTRON_VERSION=19.0.8
    npm install electron@$ELECTRON_VERSION

    pushd apps/desktop
    tmp=$(mktemp)
    jq ".electronVersion = \"${ELECTRON_VERSION}\"" electron-builder.json > "$tmp" && mv "$tmp" electron-builder.json

    %patch --strip=1 src/main/messaging.main.ts < $pkgfiles/messaging.main.ts.patch
    popd

    npm ci
build      : |
    export npm_config_build_from_source=true

    cd apps/desktop
    unset LD_PRELOAD
    npm run build && npm run clean:dist
    npm exec -c "electron-builder --linux --x64 --dir"
install    : |
    export bwdir=/usr/share/bitwarden-desktop
    install -dm00755 $installdir/usr/bin
    install -dm00755 $installdir/$bwdir

    cp -R $workdir/apps/desktop/dist/linux-unpacked/* $installdir/$bwdir/

    mv $installdir/$bwdir/bitwarden $installdir/$bwdir/bitwarden-desktop
    ln -s $bwdir/bitwarden-desktop $installdir/usr/bin/bitwarden-desktop

    install -Dm00644 $pkgfiles/bitwarden.desktop $installdir/usr/share/applications/bitwarden.desktop

    for i in 16 32 64 128 256 512 1024; do
        install -Dm00644 $workdir/apps/desktop/resources/icons/${i}x${i}.png $installdir/usr/share/icons/hicolor/${i}x${i}/apps/bitwarden.png
    done
